# **Workshop 1: Pandas Library (1)**
**คำสั่ง** 

1.   ศึกษาวิธีการใช้งาน Pandas Library เบื้องต้นต่อไปนี้
2.   ทดลองใช้งานฟังก์ชันใน Pandas Library ตามคำสั่งปฏิบัติการแต่ละข้อ
3.   ตั้งชื่อไฟล์ python notebook นี้ในรูปแบบ Lab_01_XXXXXXXXX.ipynb โดย XXXXXXXXX คือ รหัสนักศึกษา
4.   ทำการดาวน์โหลดและส่งไฟล์ Lab_01_XXXXXXXXX.ipynb ที่เว็บไซต์ http://hw.cs.science.cmu.ac.th

In [340]:
import pandas as pd
import numpy as np

**การสร้าง data frames โดยใช้ pandas library**

In [341]:
## Creating a DataFrames
# Specify values for each column.
df = pd.DataFrame({"a" : [4 ,5, 6],
                   "b" : [7, 8, 9],
                   "c" : [10, 11, 12]},
                  index = [1, 2, 3])
df.head()

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [342]:
# Specify values for each row
df = pd.DataFrame([[4, 7, 10],
                   [5, 8, 11],
                   [6, 9, 12]],
                  columns=['a', 'b', 'c'],index=[1, 2, 3])
df.head()

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

ปฏิบัติการข้อ 1) จงสร้าง data frames ที่จัดเก็บตัวแปร 3 ตัวแปร คือ ชื่อ(First Name) สกุล (Last Name) คณะ (Faculty) และ GPA ของข้อมูลนักศึกษา 5 คน ต่อไปนี้


1.   ANJIRA LUANGSAN   Science   GPA: 3.24
2.   NATTAWUT KANYA   Engineering   GPA: 2.98
3.   BENYAPHA BUABAN   Medicine   GPA: 3.67
4.   THITILUK MORASIL    Science   GPA: 3.05
5.   VIPUT UEAPITAKSAKUL   Social Science   GPA: 2.00

In [343]:
# Answer here
df = pd.DataFrame([["ANJIRA", "LUANGSAN", "Science", 3.24],
                   ["NATTAWUT", "KANYA", "Engineering", 2.98],
                   ["BENYAPHA", "BUABAN", "Medicine", 3.67],
                   ["THITILUK", "MORASIL", "Science", 3.05],
                   ["VIPUT", "UEAPITAKSAKUL", "Social Science", 2.00]],
                   columns=["First Name", "Last Name", "Faculty", "GPA"], index=[1, 2, 3, 4, 5])
df.head()

  First Name      Last Name         Faculty   GPA
1     ANJIRA       LUANGSAN         Science  3.24
2   NATTAWUT          KANYA     Engineering  2.98
3   BENYAPHA         BUABAN        Medicine  3.67
4   THITILUK        MORASIL         Science  3.05
5      VIPUT  UEAPITAKSAKUL  Social Science  2.00

**การอ่านข้อมูลจากไฟล์**

In [344]:
## Read data from CVS file
data = pd.read_csv("adult.csv")
data.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

**การสอบถามข้อมูล**

In [345]:
## Query observations 
# Query by conditions
selectedData = data[data.age >= 60]
selectedData.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
7,74,State-gov,88638,Doctorate,16,Never-married,Prof-specialty,Other-relative,White,Female,0,3683,20,United-States,>50K
8,68,Federal-gov,422013,HS-grad,9,Divorced,Prof-specialty,Not-in-family,White,Female,0,3683,40,United-States,<=50K

In [346]:
selectedData = data[(data.age >= 60) & (data['sex'] == 'Male')]
selectedData.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
24,61,?,135285,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,2603,32,United-States,<=50K
34,60,Self-emp-not-inc,205246,HS-grad,9,Never-married,Exec-managerial,Not-in-family,Black,Male,0,2559,50,United-States,>50K
44,71,?,100820,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,2489,15,United-States,<=50K
46,71,Private,110380,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,2467,52,United-States,<=50K
47,73,Self-emp-not-inc,233882,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,Asian-Pac-Islander,Male,0,2457,40,Vietnam,<=50K

In [347]:
# Query by indexes
data.iloc[10:20]

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
10,45,Private,172274,Doctorate,16,Divorced,Prof-specialty,Unmarried,Black,Female,0,3004,35,United-States,>50K
11,38,Self-emp-not-inc,164526,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,0,2824,45,United-States,>50K
12,52,Private,129177,Bachelors,13,Widowed,Other-service,Not-in-family,White,Female,0,2824,20,United-States,>50K
13,32,Private,136204,Masters,14,Separated,Exec-managerial,Not-in-family,White,Male,0,2824,55,United-States,>50K
14,51,?,172175,Doctorate,16,Never-married,?,Not-in-family,White,Male,0,2824,40,United-States,>50K
15,46,Private,45363,Prof-school,15,Divorced,Prof-specialty,Not-in-family,White,Male,0,2824,40,United-States,>50K
16,45,Private,172822,11th,7,Divorced,Transport-moving,Not-in-family,White,Male,0,2824,76,United-States,>50K
17,57,Private,317847,Masters,14,Divorced,Exec-managerial,Not-in-family,White,Male,0,2824,50,United-States,>50K
18,22,Private,119592,Assoc-acdm,12,Never-married,Handlers-cleaners,Not-in-family,Black,Male,0,2824,40,?,>50K
19,34,Private,203034,Bachelors,13,Separated,Sales,Not-in-family,White,Male,0,2824,50,United-States,>50K

In [348]:
# Select and order top n entries
data.nlargest(10, 'age')

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
199,90,Private,51744,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Male,0,2206,40,United-States,<=50K
1739,90,Local-gov,227796,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,20051,0,60,United-States,>50K
1742,90,Private,87372,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,20051,0,72,United-States,>50K
2241,90,Self-emp-not-inc,155981,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,10566,0,50,United-States,<=50K
2296,90,Private,46786,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,9386,0,15,United-States,>50K
2299,90,Private,175491,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,9386,0,50,Ecuador,>50K
2947,90,Local-gov,153602,HS-grad,9,Married-civ-spouse,Other-service,Husband,White,Male,6767,0,40,United-States,<=50K
3776,90,Self-emp-not-inc,82628,HS-grad,9,Never-married,Exec-managerial,Not-in-family,White,Male,2964,0,12,United-States,<=50K
3854,90,Local-gov,214594,7th-8th,4,Married-civ-spouse,Protective-serv,Husband,White,Male,2653,0,40,United-States,<=50K

In [349]:
# Select and order bottom n entries
data.nsmallest(5, 'age')

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
1092,17,Private,148522,11th,7,Never-married,Other-service,Own-child,White,Male,0,1721,15,United-States,<=50K
1093,17,Private,93235,12th,8,Never-married,Other-service,Own-child,White,Female,0,1721,25,United-States,<=50K
1116,17,Private,184924,9th,5,Never-married,Handlers-cleaners,Own-child,White,Male,0,1719,15,United-States,<=50K
1118,17,Private,116626,11th,7,Never-married,Handlers-cleaners,Own-child,White,Male,0,1719,18,United-States,<=50K
1235,17,Private,209949,11th,7,Never-married,Sales,Own-child,White,Female,0,1602,12,United-States,<=50K

ปฏิบัติการข้อ 2)  จงสอบถามข้อมูลที่ค่าตัวแปร occupation มีค่าเท่ากับ ?

In [350]:
# Answer here
selectedData = data[data.occupation == '?']
selectedData.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
14,51,?,172175,Doctorate,16,Never-married,?,Not-in-family,White,Male,0,2824,40,United-States,>50K
24,61,?,135285,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,2603,32,United-States,<=50K
44,71,?,100820,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,2489,15,United-States,<=50K

ปฏิบัติการข้อ 3) จงสอบถามข้อมูลของผู้หญิงทั้งหมด

In [351]:
# Answer here
selectedData = data[data.sex == "Female"]
selectedData.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

ปฏิบัติการข้อ 4) จงสอบถามข้อมูลของผู้หญิงทั้งหมดที่มีผิวขาว

In [352]:
# Answer here
selectedData = data[(data.sex == "Female") & (data["race"] == "White")]
selectedData.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
5,34,Private,216864,HS-grad,9,Divorced,Other-service,Unmarried,White,Female,0,3770,45,United-States,<=50K

ปฏิบัติการข้อ 5) จงสอบถามข้อมูลของคนที่มีชั่วโมงทำงานมากที่สุด 10 อันดับแรก

In [353]:
# Answer here
data.nlargest(10, "hours.per.week")

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
92,39,Private,348521,Some-college,10,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,2415,99,United-States,>50K
98,39,Private,237713,Prof-school,15,Married-civ-spouse,Sales,Husband,White,Male,0,2415,99,United-States,>50K
409,38,Private,111499,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,1977,99,United-States,>50K
484,31,Private,147284,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1977,99,United-States,>50K
730,43,Private,266324,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,1902,99,United-States,>50K
1881,39,Private,70995,Bachelors,13,Married-civ-spouse,Transport-moving,Husband,White,Male,15024,0,99,United-States,>50K
2023,45,Private,390368,Some-college,10,Married-civ-spouse,Sales,Husband,Black,Male,15024,0,99,United-States,>50K
2103,40,Private,25005,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,15024,0,99,United-States,>50K
2971,73,Self-emp-not-inc,102510,7th-8th,4,Married-civ-spouse,Farming-fishing,Husband,White,Male,6418,0,99,United-States,>50K
3275,49,Private,173115,10th,6,Separated,Exec-managerial,Not-in-family,Black,Male,4416,0,99,United-States,<=50K

ปฏิบัติการข้อ 6) จงเลือกข้อมูลในแถวข้อมูลที่ 30,000 ถึงข้อมูลแถวสุดท้าย

In [354]:
# Answer here
data.iloc[30000: len(data)]

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
30000,18,Private,122775,HS-grad,9,Never-married,Other-service,Own-child,White,Male,0,0,35,United-States,<=50K
30001,30,Private,329425,Some-college,10,Never-married,Protective-serv,Own-child,White,Male,0,0,48,United-States,<=50K
30002,61,Private,178312,Assoc-acdm,12,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,42,United-States,<=50K
30003,21,Private,241951,HS-grad,9,Never-married,Machine-op-inspct,Not-in-family,White,Male,0,0,45,United-States,<=50K
30004,53,Private,130143,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,48,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

**การเลือกตัวแปร**

In [355]:
## Slice Variables (Column)
# Select columns with specific names
data[['age','education','education.num']]

       age     education  education.num
0       90       HS-grad              9
1       82       HS-grad              9
2       66  Some-college             10
3       54       7th-8th              4
4       41  Some-college             10
...    ...           ...            ...
32556   22  Some-college             10
32557   27    Assoc-acdm             12
32558   40       HS-grad              9
32559   58       HS-grad              9
32560   22       HS-grad              9

[32561 rows x 3 columns]

In [356]:
# Select columns with positions
data.iloc[:,[1,2]]

      workclass  fnlwgt
0             ?   77053
1       Private  132870
2             ?  186061
3       Private  140359
4       Private  264663
...         ...     ...
32556   Private  310152
32557   Private  257302
32558   Private  154374
32559   Private  151910
32560   Private  201490

[32561 rows x 2 columns]

In [357]:
# Select all columns between two columns
data.loc[:,'education':'occupation']

          education  education.num      marital.status         occupation
0           HS-grad              9             Widowed                  ?
1           HS-grad              9             Widowed    Exec-managerial
2      Some-college             10             Widowed                  ?
3           7th-8th              4            Divorced  Machine-op-inspct
4      Some-college             10           Separated     Prof-specialty
...             ...            ...                 ...                ...
32556  Some-college             10       Never-married    Protective-serv
32557    Assoc-acdm             12  Married-civ-spouse       Tech-support
32558       HS-grad              9  Married-civ-spouse  Machine-op-inspct
32559       HS-grad              9             Widowed       Adm-clerical
32560       HS-grad              9       Never-married       Adm-clerical

[32561 rows x 4 columns]

In [358]:
# Select columns by regular expression
data.filter(regex='^capital.')

       capital.gain  capital.loss
0                 0          4356
1                 0          4356
2                 0          4356
3                 0          3900
4                 0          3900
...             ...           ...
32556             0             0
32557             0             0
32558             0             0
32559             0             0
32560             0             0

[32561 rows x 2 columns]

ปฏิบัติการข้อ 7) จงเลือกตัวแปรที่ขึ้นต้นด้วยคำว่า education

In [359]:
# Answer here
data.filter(regex='^education')

          education  education.num
0           HS-grad              9
1           HS-grad              9
2      Some-college             10
3           7th-8th              4
4      Some-college             10
...             ...            ...
32556  Some-college             10
32557    Assoc-acdm             12
32558       HS-grad              9
32559       HS-grad              9
32560       HS-grad              9

[32561 rows x 2 columns]

ปฏิบัติการข้อ 8) จงเลือกข้อมูลของคนที่มีชั่วโมงทำงานน้อยกว่าหรือเท่ากับ 15 ชั่วโมง และนำมาเฉพาะค่าตัวแปร education และ age

In [360]:
# Answer here
data.loc[data["hours.per.week"] <= 15, ["education", "age"]]

          education  age
44          HS-grad   71
62     Some-college   44
76        Assoc-voc   41
114       Doctorate   72
124       Bachelors   70
...             ...  ...
32500       HS-grad   82
32527    Assoc-acdm   26
32528     Assoc-voc   81
32541     Doctorate   71
32554       Masters   32

[1381 rows x 2 columns]

**การเข้าถึงและแก้ไขข้อมูล**

In [361]:
## access data
print(data.loc[15])
print(data.loc[0:5,['age','sex']])

age                           46
workclass                Private
fnlwgt                     45363
education            Prof-school
education.num                 15
marital.status          Divorced
occupation        Prof-specialty
relationship       Not-in-family
race                       White
sex                         Male
capital.gain                   0
capital.loss                2824
hours.per.week                40
native.country     United-States
income                      >50K
Name: 15, dtype: object
   age     sex
0   90  Female
1   82  Female
2   66  Female
3   54  Female
4   41  Female
5   34  Female

In [362]:
## Maniplate data
data.loc[0,['age']] = 50
data.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,50,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [363]:
data.loc[data.workclass == '?',['workclass']] = np.nan
data.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,50,NaN,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,NaN,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

ปฏิบัติการข้อ 9) จงแทนค่าตัวแปร occupation ที่มีค่าเท่ากับ ? ด้วยค่า NaN

In [364]:
# Answer here
data.loc[data.occupation == '?', ["occupation"]] = np.nan
data.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,50,NaN,77053,HS-grad,9,Widowed,NaN,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,NaN,186061,Some-college,10,Widowed,NaN,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

**การคำนวณค่าสถิติเชิงพรรณนาสำหรับอธิบายข้อมูล**

In [365]:
## Summarize data
# - value_counts()
# - nunique()
# - describe()
# - sum() 
# - count() 
# - median() 
# - quantile([0.25,0.75])
# - min() 
# - max() 
# - mean() 
# - var() 
# - std()
data['age'].quantile([0.25,0.75])

0.25    28.0
0.75    48.0
Name: age, dtype: float64

ปฏิบัติการข้อ 10) จงคำนวณคำสำหรับอธิบายลักษณะการกระจายของตัวแปร education.num

In [366]:
# Answer here
data["education.num"].var()

np.float64(6.618889907032931)

ปฏิบัติการข้อ 11) จงหาค่าที่เป็นไปได้ทั้งหมดของตัวแปร education

In [367]:
# Answer here

**การวนเข้าถึงข้อมูลแต่ละแถว**

In [368]:
## Iterate over rows 
for index, row in data.iterrows():
    print(index, row['marital.status'])

0 Widowed
1 Widowed
2 Widowed
3 Divorced
4 Separated
5 Divorced
6 Separated
7 Never-married
8 Divorced
9 Never-married
10 Divorced
11 Never-married
12 Widowed
13 Separated
14 Never-married
15 Divorced
16 Divorced
17 Divorced
18 Never-married
19 Separated
20 Never-married
21 Separated
22 Divorced
23 Married-civ-spouse
24 Married-civ-spouse
25 Married-civ-spouse
26 Married-civ-spouse
27 Married-civ-spouse
28 Never-married
29 Never-married
30 Separated
31 Widowed
32 Divorced
33 Divorced
34 Never-married
35 Divorced
36 Never-married
37 Never-married
38 Never-married
39 Divorced
40 Divorced
41 Divorced
42 Divorced
43 Divorced
44 Married-civ-spouse
45 Married-spouse-absent
46 Married-civ-spouse
47 Married-civ-spouse
48 Married-civ-spouse
49 Married-civ-spouse
50 Never-married
51 Widowed
52 Divorced
53 Never-married
54 Never-married
55 Never-married
56 Separated
57 Never-married
58 Never-married
59 Separated
60 Divorced
61 Never-married
62 Married-civ-spouse
63 Married-civ-spouse
64 Married-civ-spouse
65 Married-civ-spouse
66 Married-civ-spouse
67 Married-civ-spouse
68 Married-civ-spouse
69 Married-civ-spouse
70 Married-civ-spouse
71 Married-civ-spouse
72 Married-civ-spouse
73 Married-civ-spouse
74 Married-civ-spouse
75 Married-civ-spouse
76 Married-civ-spouse
77 Married-civ-spouse
78 Married-civ-spouse
79 Married-civ-spouse
80 Married-civ-spouse
81 Married-civ-spouse
82 Married-civ-spouse
83 Married-civ-spouse
84 Married-civ-spouse
85 Married-civ-spouse
86 Married-civ-spouse
87 Married-civ-spouse
88 Married-civ-spouse
89 Married-civ-spouse
90 Married-civ-spouse
91 Married-civ-spouse
92 Married-civ-spouse
93 Married-civ-spouse
94 Married-civ-spouse
95 Married-civ-spouse
96 Married-civ-spouse
97 Married-civ-spouse
98 Married-civ-spouse
99 Married-civ-spouse
100 Married-civ-spouse
101 Married-civ-spouse
102 Married-civ-spouse
103 Married-civ-spouse
104 Married-civ-spouse
105 Married-civ-spouse
106 Married-civ-spouse
107 Married-civ-spouse
108 Married-civ-spouse
109 Married-civ-spouse
110 Married-civ-spouse
111 Widowed
112 Married-civ-spouse
113 Married-civ-spouse
114 Married-civ-spouse
115 Married-civ-spouse
116 Married-civ-spouse
117 Married-civ-spouse
118 Married-civ-spouse
119 Married-civ-spouse
120 Married-civ-spouse
121 Married-civ-spouse
122 Married-civ-spouse
123 Married-civ-spouse
124 Married-civ-spouse
125 Married-civ-spouse
126 Married-civ-spouse
127 Married-civ-spouse
128 Married-civ-spouse
129 Married-civ-spouse
130 Married-civ-spouse
131 Married-civ-spouse
132 Married-civ-spouse
133 Married-civ-spouse
134 Married-civ-spouse
135 Married-civ-spouse
136 Married-civ-spouse
137 Married-civ-spouse
138 Married-civ-spouse
139 Married-civ-spouse
140 Married-civ-spouse
141 Married-civ-spouse
142 Divorced
143 Never-married
144 Widowed
145 Never-married
146 Divorced
147 Divorced
148 Married-spouse-absent
149 Never-married
150 Never-married
151 Separated
152 Separated
153 Widowed
154 Divorced
155 Divorced
156 Never-married
157 Never-married
158 Divorced
159 Widowed
160 Married-civ-spouse
161 Married-civ-spouse
162 Married-civ-spouse
163 Never-married
164 Never-married
165 Divorced
166 Never-married
167 Never-married
168 Separated
169 Divorced
170 Never-married
171 Never-married
172 Never-married
173 Divorced
174 Never-married
175 Never-married
176 Never-married
177 Never-married
178 Divorced
179 Never-married
180 Widowed
181 Never-married
182 Divorced
183 Never-married
184 Never-married
185 Widowed
186 Divorced
187 Divorced
188 Married-civ-spouse
189 Married-civ-spouse
190 Married-civ-spouse
191 Married-civ-spouse
192 Married-civ-spouse
193 Married-civ-spouse
194 Separated
195 Widowed
196 Never-married
197 Widowed
198 Never-married
199 Never-married
200 Widowed
201 Divorced
202 Widowed
203 Divorced
204 Widowed
205 Never-married
206 Divorced
207 Never-married
208 Never-married
209 Divorced
210 Never-married
211 Never-married
212 Never-married
213 Divorced
214 Divorced
215 Married-civ-spouse
216 Married-civ-spouse
217 Married-civ-spouse
218 Married-civ-spouse
219 Married-civ-spouse
220 Married-civ-spouse
221 Married-civ-spouse
222 Married-civ-spouse
223 Married-civ-spouse
224 Married-civ-spouse
225 Married-civ-spouse
226 Married-civ-spouse
227 Married-civ-spouse
228 Married-civ-spouse
229 Married-civ-spouse
230 Married-civ-spouse
231 Married-civ-spouse
232 Married-civ-spouse
233 Married-civ-spouse
234 Married-civ-spouse
235 Married-civ-spouse
236 Married-civ-spouse
237 Married-civ-spouse
238 Married-civ-spouse
239 Married-civ-spouse
240 Married-civ-spouse
241 Married-civ-spouse
242 Married-civ-spouse
243 Divorced
244 Married-civ-spouse
245 Married-civ-spouse
246 Married-civ-spouse
247 Married-civ-spouse
248 Married-civ-spouse
249 Married-civ-spouse
250 Married-civ-spouse
251 Married-civ-spouse
252 Married-civ-spouse
253 Married-civ-spouse
254 Married-civ-spouse
255 Married-civ-spouse
256 Married-civ-spouse
257 Married-civ-spouse
258 Married-civ-spouse
259 Married-civ-spouse
260 Married-civ-spouse
261 Married-civ-spouse
262 Married-civ-spouse
263 Married-civ-spouse
264 Married-civ-spouse
265 Married-civ-spouse
266 Married-civ-spouse
267 Married-civ-spouse
268 Married-civ-spouse
269 Married-civ-spouse
270 Married-civ-spouse
271 Married-civ-spouse
272 Married-civ-spouse
273 Married-civ-spouse
274 Married-civ-spouse
275 Married-civ-spouse
276 Married-civ-spouse
277 Married-civ-spouse
278 Married-civ-spouse
279 Married-civ-spouse
280 Married-civ-spouse
281 Married-civ-spouse
282 Married-civ-spouse
283 Married-civ-spouse
284 Married-civ-spouse
285 Married-civ-spouse
286 Married-civ-spouse
287 Married-civ-spouse
288 Married-civ-spouse
289 Married-civ-spouse
290 Married-civ-spouse
291 Married-civ-spouse
292 Married-civ-spouse
293 Married-civ-spouse
294 Married-civ-spouse
295 Married-civ-spouse
296 Married-civ-spouse
297 Married-civ-spouse
298 Married-civ-spouse
299 Married-civ-spouse
300 Married-civ-spouse
301 Never-married
302 Never-married
303 Never-married
304 Divorced
305 Never-married
306 Never-married
307 Never-married
308 Never-married
309 Never-married
310 Separated
311 Divorced
312 Widowed
313 Never-married
314 Never-married
315 Never-married
316 Never-married
317 Never-married
318 Never-married
319 Never-married
320 Never-married
321 Separated
322 Never-married
323 Never-married
324 Never-married
325 Never-married
326 Never-married
327 Divorced
328 Married-spouse-absent
329 Never-married
330 Never-married
331 Divorced
332 Separated
333 Divorced
334 Never-married
335 Never-married
336 Widowed
337 Divorced
338 Divorced
339 Never-married
340 Never-married
341 Separated
342 Never-married
343 Never-married
344 Divorced
345 Divorced
346 Never-married
347 Never-married
348 Married-civ-spouse
349 Married-civ-spouse
350 Married-civ-spouse
351 Married-civ-spouse
352 Married-civ-spouse
353 Married-civ-spouse
354 Married-civ-spouse
355 Married-civ-spouse
356 Married-civ-spouse
357 Married-civ-spouse
358 Married-civ-spouse
359 Married-civ-spouse
360 Married-civ-spouse
361 Married-civ-spouse
362 Married-civ-spouse
363 Married-civ-spouse
364 Married-civ-spouse
365 Married-civ-spouse
366 Married-civ-spouse
367 Married-civ-spouse
368 Married-civ-spouse
369 Married-civ-spouse
370 Married-civ-spouse
371 Married-civ-spouse
372 Married-civ-spouse
373 Married-civ-spouse
374 Married-civ-spouse
375 Married-civ-spouse
376 Married-civ-spouse
377 Married-civ-spouse
378 Married-civ-spouse
379 Married-civ-spouse
380 Married-civ-spouse
381 Married-civ-spouse
382 Married-civ-spouse
383 Married-civ-spouse
384 Married-civ-spouse
385 Married-civ-spouse
386 Married-civ-spouse
387 Married-civ-spouse
388 Married-civ-spouse
389 Married-civ-spouse
390 Married-civ-spouse
391 Married-civ-spouse
392 Married-civ-spouse
393 Married-civ-spouse
394 Married-civ-spouse
395 Married-civ-spouse
396 Married-civ-spouse
397 Married-civ-spouse
398 Married-civ-spouse
399 Married-civ-spouse
400 Married-civ-spouse
401 Married-civ-spouse
402 Married-civ-spouse
403 Married-civ-spouse
404 Married-civ-spouse
405 Married-civ-spouse
406 Married-civ-spouse
407 Married-civ-spouse
408 Married-civ-spouse
409 Married-civ-spouse
410 Married-civ-spouse
411 Married-civ-spouse
412 Married-civ-spouse
413 Married-civ-spouse
414 Married-civ-spouse
415 Married-civ-spouse
416 Married-civ-spouse
417 Married-civ-spouse
418 Married-civ-spouse
419 Married-civ-spouse
420 Married-civ-spouse
421 Married-civ-spouse
422 Married-civ-spouse
423 Married-civ-spouse
424 Married-civ-spouse
425 Married-civ-spouse
426 Married-civ-spouse
427 Married-civ-spouse
428 Married-civ-spouse
429 Married-civ-spouse
430 Married-civ-spouse
431 Married-civ-spouse
432 Married-civ-spouse
433 Married-civ-spouse
434 Married-civ-spouse
435 Married-civ-spouse
436 Married-civ-spouse
437 Married-civ-spouse
438 Married-civ-spouse
439 Married-civ-spouse
440 Married-civ-spouse
441 Married-civ-spouse
442 Married-civ-spouse
443 Married-civ-spouse
444 Married-civ-spouse
445 Married-civ-spouse
446 Married-civ-spouse
447 Married-civ-spouse
448 Married-civ-spouse
449 Married-civ-spouse
450 Married-civ-spouse
451 Married-civ-spouse
452 Married-civ-spouse
453 Married-civ-spouse
454 Married-civ-spouse
455 Married-civ-spouse
456 Married-civ-spouse
457 Married-civ-spouse
458 Married-civ-spouse
459 Married-civ-spouse
460 Married-civ-spouse
461 Married-civ-spouse
462 Married-civ-spouse
463 Married-civ-spouse
464 Married-civ-spouse
465 Married-civ-spouse
466 Married-civ-spouse
467 Married-civ-spouse
468 Married-civ-spouse
469 Married-civ-spouse
470 Married-civ-spouse
471 Married-civ-spouse
472 Married-civ-spouse
473 Married-civ-spouse
474 Married-civ-spouse
475 Married-civ-spouse
476 Married-civ-spouse
477 Married-civ-spouse
478 Married-civ-spouse
479 Married-civ-spouse
480 Married-civ-spouse
481 Married-civ-spouse
482 Married-civ-spouse
483 Married-civ-spouse
484 Married-civ-spouse
485 Married-civ-spouse
486 Married-civ-spouse
487 Married-civ-spouse
488 Married-civ-spouse
489 Married-civ-spouse
490 Married-civ-spouse
491 Married-civ-spouse
492 Married-civ-spouse
493 Married-civ-spouse
494 Married-civ-spouse
495 Married-civ-spouse
496 Married-civ-spouse
497 Married-civ-spouse
498 Married-civ-spouse
499 Married-civ-spouse
500 Married-civ-spouse
501 Married-civ-spouse
502 Married-civ-spouse
503 Married-civ-spouse
504 Married-civ-spouse
505 Married-civ-spouse
506 Married-civ-spouse
507 Married-civ-spouse
508 Married-civ-spouse
509 Married-civ-spouse
510 Married-civ-spouse
511 Married-civ-spouse
512 Married-civ-spouse
513 Married-civ-spouse
514 Married-civ-spouse
515 Married-civ-spouse
516 Never-married
517 Never-married
518 Never-married
519 Divorced
520 Never-married
521 Never-married
522 Never-married
523 Never-married
524 Divorced
525 Never-married
526 Separated
527 Widowed
528 Never-married
529 Never-married
530 Never-married
531 Never-married
532 Never-married
533 Divorced
534 Widowed
535 Married-civ-spouse
536 Married-civ-spouse
537 Married-civ-spouse
538 Married-civ-spouse
539 Married-civ-spouse
540 Married-civ-spouse
541 Married-civ-spouse
542 Married-civ-spouse
543 Married-civ-spouse
544 Married-civ-spouse
545 Married-civ-spouse
546 Married-civ-spouse
547 Married-civ-spouse
548 Married-civ-spouse
549 Married-civ-spouse
550 Married-civ-spouse
551 Married-civ-spouse
552 Married-civ-spouse
553 Married-civ-spouse
554 Married-civ-spouse
555 Married-civ-spouse
556 Married-civ-spouse
557 Married-civ-spouse
558 Married-civ-spouse
559 Married-civ-spouse
560 Married-civ-spouse
561 Married-civ-spouse
562 Married-civ-spouse
563 Married-civ-spouse
564 Married-civ-spouse
565 Married-civ-spouse
566 Married-civ-spouse
567 Married-civ-spouse
568 Married-civ-spouse
569 Married-civ-spouse
570 Married-civ-spouse
571 Married-civ-spouse
572 Married-civ-spouse
573 Married-civ-spouse
574 Married-civ-spouse
575 Married-civ-spouse
576 Married-civ-spouse
577 Married-civ-spouse
578 Married-civ-spouse
579 Married-civ-spouse
580 Married-civ-spouse
581 Married-civ-spouse
582 Married-civ-spouse
583 Married-civ-spouse
584 Married-civ-spouse
585 Married-civ-spouse
586 Married-civ-spouse
587 Married-civ-spouse
588 Married-civ-spouse
589 Married-civ-spouse
590 Married-civ-spouse
591 Married-civ-spouse
592 Married-civ-spouse
593 Married-civ-spouse
594 Married-civ-spouse
595 Married-civ-spouse
596 Married-civ-spouse
597 Married-civ-spouse
598 Married-civ-spouse
599 Married-civ-spouse
600 Married-civ-spouse
601 Married-civ-spouse
602 Married-civ-spouse
603 Married-civ-spouse
604 Married-civ-spouse
605 Married-civ-spouse
606 Married-civ-spouse
607 Married-civ-spouse
608 Married-civ-spouse
609 Married-civ-spouse
610 Married-civ-spouse
611 Married-civ-spouse
612 Married-civ-spouse
613 Married-civ-spouse
614 Married-civ-spouse
615 Married-civ-spouse
616 Married-civ-spouse
617 Married-civ-spouse
618 Married-civ-spouse
619 Married-civ-spouse
620 Married-civ-spouse
621 Married-civ-spouse
622 Married-civ-spouse
623 Married-civ-spouse
624 Married-civ-spouse
625 Married-civ-spouse
626 Married-civ-spouse
627 Married-civ-spouse
628 Married-civ-spouse
629 Married-civ-spouse
630 Married-civ-spouse
631 Married-civ-spouse
632 Married-civ-spouse
633 Married-civ-spouse
634 Married-civ-spouse
635 Married-civ-spouse
636 Married-civ-spouse
637 Married-civ-spouse
638 Married-civ-spouse
639 Married-civ-spouse
640 Married-civ-spouse
641 Married-civ-spouse
642 Married-civ-spouse
643 Married-civ-spouse
644 Married-civ-spouse
645 Married-civ-spouse
646 Married-civ-spouse
647 Married-civ-spouse
648 Married-civ-spouse
649 Married-civ-spouse
650 Married-civ-spouse
651 Married-civ-spouse
652 Married-civ-spouse
653 Married-civ-spouse
654 Married-civ-spouse
655 Married-civ-spouse
656 Married-civ-spouse
657 Married-civ-spouse
658 Married-civ-spouse
659 Married-civ-spouse
660 Married-civ-spouse
661 Married-civ-spouse
662 Married-civ-spouse
663 Married-civ-spouse
664 Married-civ-spouse
665 Married-civ-spouse
666 Married-civ-spouse
667 Married-civ-spouse
668 Married-civ-spouse
669 Married-civ-spouse
670 Married-civ-spouse
671 Married-civ-spouse
672 Married-civ-spouse
673 Married-civ-spouse
674 Married-civ-spouse
675 Married-civ-spouse
676 Married-civ-spouse
677 Married-civ-spouse
678 Married-civ-spouse
679 Married-civ-spouse
680 Married-civ-spouse
681 Married-civ-spouse
682 Married-civ-spouse
683 Married-civ-spouse
684 Married-civ-spouse
685 Married-civ-spouse
686 Married-civ-spouse
687 Married-civ-spouse
688 Married-civ-spouse
689 Married-civ-spouse
690 Married-civ-spouse
691 Married-civ-spouse
692 Married-civ-spouse
693 Married-civ-spouse
694 Married-civ-spouse
695 Married-civ-spouse
696 Married-civ-spouse
697 Married-civ-spouse
698 Married-civ-spouse
699 Married-civ-spouse
700 Married-civ-spouse
701 Married-civ-spouse
702 Married-civ-spouse
703 Married-civ-spouse
704 Married-civ-spouse
705 Married-civ-spouse
706 Married-civ-spouse
707 Married-civ-spouse
708 Married-civ-spouse
709 Married-civ-spouse
710 Married-civ-spouse
711 Married-civ-spouse
712 Married-civ-spouse
713 Married-civ-spouse
714 Married-civ-spouse
715 Married-civ-spouse
716 Married-civ-spouse
717 Married-civ-spouse
718 Married-civ-spouse
719 Married-civ-spouse
720 Married-civ-spouse
721 Married-civ-spouse
722 Married-civ-spouse
723 Married-civ-spouse
724 Married-civ-spouse
725 Married-civ-spouse
726 Married-civ-spouse
727 Married-civ-spouse
728 Married-civ-spouse
729 Married-civ-spouse
730 Married-civ-spouse
731 Married-civ-spouse
732 Married-civ-spouse
733 Married-civ-spouse
734 Married-civ-spouse
735 Married-civ-spouse
736 Married-civ-spouse
737 Married-civ-spouse
738 Married-civ-spouse
739 Married-civ-spouse
740 Married-civ-spouse
741 Married-civ-spouse
742 Married-civ-spouse
743 Married-civ-spouse
744 Married-civ-spouse
745 Married-civ-spouse
746 Married-civ-spouse
747 Married-civ-spouse
748 Married-civ-spouse
749 Married-civ-spouse
750 Married-civ-spouse
751 Married-civ-spouse
752 Married-civ-spouse
753 Married-civ-spouse
754 Married-civ-spouse
755 Married-civ-spouse
756 Married-civ-spouse
757 Married-civ-spouse
758 Married-civ-spouse
759 Married-civ-spouse
760 Married-civ-spouse
761 Married-civ-spouse
762 Married-civ-spouse
763 Married-civ-spouse
764 Married-civ-spouse
765 Married-civ-spouse
766 Married-civ-spouse
767 Married-civ-spouse
768 Married-civ-spouse
769 Married-civ-spouse
770 Married-civ-spouse
771 Married-civ-spouse
772 Married-civ-spouse
773 Married-civ-spouse
774 Married-civ-spouse
775 Married-civ-spouse
776 Married-civ-spouse
777 Married-civ-spouse
778 Married-civ-spouse
779 Married-civ-spouse
780 Married-civ-spouse
781 Married-civ-spouse
782 Married-civ-spouse
783 Married-civ-spouse
784 Married-civ-spouse
785 Married-civ-spouse
786 Married-civ-spouse
787 Married-civ-spouse
788 Married-civ-spouse
789 Married-civ-spouse
790 Married-civ-spouse
791 Married-civ-spouse
792 Married-civ-spouse
793 Married-civ-spouse
794 Married-civ-spouse
795 Married-civ-spouse
796 Married-civ-spouse
797 Married-civ-spouse
798 Married-civ-spouse
799 Married-civ-spouse
800 Married-civ-spouse
801 Married-civ-spouse
802 Married-civ-spouse
803 Married-civ-spouse
804 Married-civ-spouse
805 Married-civ-spouse
806 Married-civ-spouse
807 Married-civ-spouse
808 Married-civ-spouse
809 Married-civ-spouse
810 Married-civ-spouse
811 Married-civ-spouse
812 Married-civ-spouse
813 Married-civ-spouse
814 Married-civ-spouse
815 Married-civ-spouse
816 Married-civ-spouse
817 Married-civ-spouse
818 Married-civ-spouse
819 Married-civ-spouse
820 Married-civ-spouse
821 Married-civ-spouse
822 Married-civ-spouse
823 Married-civ-spouse
824 Married-civ-spouse
825 Married-civ-spouse
826 Married-civ-spouse
827 Married-civ-spouse
828 Married-civ-spouse
829 Married-civ-spouse
830 Married-civ-spouse
831 Married-civ-spouse
832 Married-civ-spouse
833 Married-civ-spouse
834 Married-civ-spouse
835 Married-civ-spouse
836 Married-civ-spouse
837 Married-civ-spouse
838 Married-civ-spouse
839 Married-civ-spouse
840 Married-civ-spouse
841 Married-civ-spouse
842 Married-civ-spouse
843 Married-civ-spouse
844 Married-civ-spouse
845 Married-civ-spouse
846 Married-civ-spouse
847 Married-civ-spouse
848 Married-civ-spouse
849 Married-civ-spouse
850 Married-civ-spouse
851 Married-civ-spouse
852 Married-civ-spouse
853 Married-civ-spouse
854 Married-civ-spouse
855 Married-civ-spouse
856 Married-civ-spouse
857 Married-civ-spouse
858 Married-civ-spouse
859 Married-civ-spouse
860 Married-civ-spouse
861 Married-civ-spouse
862 Married-civ-spouse
863 Married-civ-spouse
864 Married-civ-spouse
865 Married-civ-spouse
866 Married-civ-spouse
867 Married-civ-spouse
868 Married-civ-spouse
869 Married-civ-spouse
870 Married-civ-spouse
871 Married-civ-spouse
872 Married-civ-spouse
873 Married-civ-spouse
874 Married-civ-spouse
875 Married-civ-spouse
876 Married-civ-spouse
877 Married-civ-spouse
878 Married-civ-spouse
879 Married-civ-spouse
880 Married-civ-spouse
881 Married-civ-spouse
882 Married-civ-spouse
883 Married-civ-spouse
884 Married-civ-spouse
885 Married-civ-spouse
886 Married-civ-spouse
887 Married-civ-spouse
888 Married-civ-spouse
889 Married-civ-spouse
890 Married-civ-spouse
891 Married-civ-spouse
892 Married-civ-spouse
893 Married-civ-spouse
894 Married-civ-spouse
895 Married-civ-spouse
896 Never-married
897 Never-married
898 Divorced
899 Never-married
900 Divorced
901 Never-married
902 Separated
903 Divorced
904 Divorced
905 Divorced
906 Never-married
907 Never-married
908 Never-married
909 Divorced
910 Never-married
911 Separated
912 Never-married
913 Divorced
914 Never-married
915 Never-married
916 Separated
917 Divorced
918 Divorced
919 Never-married
920 Divorced
921 Never-married
922 Divorced
923 Never-married
924 Never-married
925 Never-married
926 Never-married
927 Divorced
928 Never-married
929 Never-married
930 Divorced
931 Divorced
932 Divorced
933 Divorced
934 Separated
935 Married-civ-spouse
936 Married-civ-spouse
937 Married-civ-spouse
938 Married-civ-spouse
939 Married-civ-spouse
940 Married-civ-spouse
941 Married-civ-spouse
942 Married-civ-spouse
943 Married-civ-spouse
944 Married-civ-spouse

ปฏิบัติการข้อ 12) จงคำนวณค่าเฉลี่ยอายุของข้อมูลทั้งหมดโดย*ไม่ใช้*ฟังก์ชัน mean หรือ average

In [369]:
# Answer here
avg_age = 0

for index, row in data.iterrows():
    avg_age += row['age']
avg_age /= len(data)

print(avg_age)

38.5804182918215

ปฏิบัติการข้อ 13) จงคำนวณผลกำไร (profit) จากการลงทุน (Capital)  และจัดเก็บเป็นอีกตัวแปรหนึ่ง ชื่อ profit ของข้อมูลแต่ละคน แล้วคำนวณค่าเฉลี่ยผลกำไร

In [370]:
# Answer here